const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const MARKER = '# @generated withFmtCxx17Fix';

// React Native's pinned "fmt" pod (a Folly dependency) uses FMT_STRING
// macros gated on C++20 consteval support. Newer Xcode/Clang versions
// reject fmt's consteval usage as a non-constant expression, failing the
// build with "call to consteval function ... is not a constant expression".
// Forcing this one pod target to C++17 sidesteps the consteval codepath
// (fmt falls back to constexpr) without touching any other pod's language
// standard. ios/ is regenerated by `expo prebuild`, so this has to be a
// plugin, not a one-off Podfile edit.
//
// CocoaPods only allows a single `post_install` hook per Podfile, so this
// injects into the existing one (generated by the RN/Expo template) rather
// than appending a second block. It must run AFTER react_native_post_install
// -- that helper (scripts/cocoapods/new_architecture.rb, when newArchEnabled)
// sets CLANG_CXX_LANGUAGE_STANDARD on pod targets itself, clobbering an
// override placed earlier in the block.
function withFmtCxx17Fix(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfilePath, 'utf8');
      if (contents.includes(MARKER)) return config;

      const hookBody = `
    ${MARKER}
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |build_config|
          build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++17'
        end
      end
    end
`;

      // Insert right after react_native_post_install(...)'s closing paren
      // line, not at the top of the block -- see comment above.
      const updated = contents.replace(
        /(react_native_post_install\(\n(?:.*\n)*?\s*\)\n)/,
        (match) => match + hookBody,
      );
      if (updated === contents) {
        throw new Error('withFmtCxx17Fix: could not find `react_native_post_install(...)` call in the generated Podfile');
      }

      fs.writeFileSync(podfilePath, updated);
      return config;
    },
  ]);
}

module.exports = withFmtCxx17Fix;
